root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main -f ./samples/nanomon.yaml"
  cmd = "go build -o ./tmp/main ./src"
  include_ext = ["go", "json"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
